---
- name: eval-devops
  hosts: 127.0.0.1
  tasks:
    - name: Pull Camioned Docker image
      docker_image:
        name: camioned-front:latest
        source: pull
        repository: ghcr.io/denwo-1/camioned-front:latest

    - name: Run Camioned Docker container
      docker_container:
        name: camioned-front
        image: camioned-front:latest
        ports:
          - "80:80"
        volumes:
          - /var/www:/var/www